"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Building2, Image as ImageIcon, LogOut, Pencil, Plus, Trash2 } from "lucide-react";
import { ApiError, createHotel, deleteHotel, Hotel, HotelInput, hotelsLogin, hotelsLogout, hotelsMe, HotelsUser, listHotels, updateHotel } from "@/lib/api";

const empty: HotelInput = { name: "", locality: "", address: "", photo_url: "", report_amount: 0, actual_price: null, notes: "" };
const money = (value: number) => new Intl.NumberFormat("ru-RU").format(value) + " ₽";

export default function HotelsPage() {
  const [user, setUser] = useState<HotelsUser | null>(null), [loading, setLoading] = useState(true);
  const [hotels, setHotels] = useState<Hotel[]>([]), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [query, setQuery] = useState(""), [locality, setLocality] = useState(""), [sort, setSort] = useState("name");
  const [editing, setEditing] = useState<Hotel | null | "new">(null);
  async function load() { setError(""); try { setHotels(await listHotels()); } catch (e) { if (e instanceof ApiError && e.status === 401) setUser(null); else setError("Не удалось загрузить список гостиниц"); } }
  useEffect(() => { hotelsMe().then(u => { setUser(u); return load(); }).catch(() => setUser(null)).finally(() => setLoading(false)); }, []);
  const localities = useMemo(() => Array.from(new Set(hotels.map(h => h.locality).filter(Boolean))).sort(), [hotels]);
  const shown = useMemo(() => hotels.filter(h => !locality || h.locality === locality).filter(h => [h.name,h.locality,h.address,h.notes].join(" ").toLocaleLowerCase("ru").includes(query.trim().toLocaleLowerCase("ru"))).sort((a,b) => sort === "asc" ? a.report_amount-b.report_amount : sort === "desc" ? b.report_amount-a.report_amount : a.name.localeCompare(b.name,"ru")), [hotels,query,locality,sort]);
  if (loading) return <main className="grid min-h-screen place-items-center text-muted">Загрузка…</main>;
  if (!user) return <Login onLogin={async (surname,password) => { const u=await hotelsLogin(surname,password); setUser(u); await load(); }} />;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#eef8ff,transparent_34%),linear-gradient(180deg,#fff_0%,#f7f9fc_100%)] px-5 py-8 sm:px-8 lg:px-12">
    <div className="mx-auto max-w-screen-2xl">
      <header className="flex flex-wrap items-start justify-between gap-4"><div><a href="/" className="text-sm font-semibold text-brand">← Поиск маршрута</a><h1 className="mt-3 text-4xl font-semibold text-ink">Гостиницы</h1><p className="mt-2 text-muted">Корпоративный справочник гостиниц для командировок</p></div><div className="flex items-center gap-3 rounded-2xl border border-line bg-white p-2 pl-4 shadow-soft"><b>{user.surname}</b><button onClick={async()=>{await hotelsLogout();setUser(null)}} className="flex gap-2 rounded-xl bg-ink px-4 py-2 text-white"><LogOut size={18}/>Выйти</button></div></header>
      <section className="mt-8 flex flex-wrap gap-3 rounded-[2rem] border border-line bg-white p-5 shadow-card"><input aria-label="Поиск гостиницы" placeholder="Поиск гостиницы" value={query} onChange={e=>setQuery(e.target.value)} className="min-w-64 flex-1 rounded-xl border border-line px-4 py-3"/><select aria-label="Населённый пункт" value={locality} onChange={e=>setLocality(e.target.value)} className="rounded-xl border border-line px-4"><option value="">Все города</option>{localities.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Сортировка" value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border border-line px-4"><option value="name">По названию</option><option value="asc">Сумма по отчёту: сначала меньше</option><option value="desc">Сумма по отчёту: сначала больше</option></select>{user.is_admin&&<button onClick={()=>setEditing("new")} className="flex items-center gap-2 rounded-xl bg-brand px-4 py-3 font-semibold text-white"><Plus size={18}/>Добавить гостиницу</button>}</section>
      {error&&<div className="mt-5 rounded-2xl bg-rose-50 p-4 text-rose-700">{error} <button className="ml-3 underline" onClick={load}>Повторить</button></div>}{notice&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-emerald-700">{notice}</div>}
      {!error&&shown.length===0?<p className="py-20 text-center text-muted">По вашему запросу гостиницы не найдены</p>:<div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{shown.map(h=><article key={h.id} className="overflow-hidden rounded-[2rem] border border-line bg-white shadow-card"><div className="flex h-44 items-center justify-center bg-cloud">{h.photo_url?<img src={h.photo_url} alt="" className="h-full w-full object-cover"/>:<div className="text-center text-muted"><ImageIcon className="mx-auto mb-2"/>Фото отсутствует</div>}</div><div className="p-6"><h2 className="text-xl font-semibold">{h.name}</h2>{h.locality&&<p className="mt-1 text-brand">{h.locality}</p>}<p className="mt-3 text-sm text-muted">{h.address||"Адрес не указан"}</p><p className="mt-5 rounded-xl bg-sky-50 p-3 font-semibold text-brand">Сумма по отчёту: {money(h.report_amount)}</p>{h.actual_price!==null&&<p className="mt-3 text-sm">Фактическая стоимость: {money(h.actual_price)}</p>}{h.notes&&<p className="mt-3 whitespace-pre-wrap text-sm text-muted">{h.notes}</p>}{user.is_admin&&<div className="mt-5 flex gap-2"><button onClick={()=>setEditing(h)} className="flex gap-2 rounded-xl border border-line px-3 py-2"><Pencil size={16}/>Изменить</button><button onClick={async()=>{if(confirm(`Удалить гостиницу «${h.name}»?`)){try{await deleteHotel(h.id);setNotice("Гостиница удалена");await load()}catch(e){setError(e instanceof ApiError&&e.status===403?"Недостаточно прав":"Не удалось удалить гостиницу")}}}} className="flex gap-2 rounded-xl border border-rose-200 px-3 py-2 text-rose-700"><Trash2 size={16}/>Удалить</button></div>}</div></article>)}</div>}
    </div>{editing&&<Editor hotel={editing==="new"?null:editing} onClose={()=>setEditing(null)} onSave={async value=>{try{editing==="new"?await createHotel(value):await updateHotel(editing.id,value);setEditing(null);setNotice("Изменения сохранены");await load()}catch(e){setError(e instanceof ApiError&&e.status===403?"Недостаточно прав":"Не удалось сохранить гостиницу")}}}/>}</main>;
}

function Login({onLogin}:{onLogin:(s:string,p:string)=>Promise<void>}) { const [surname,setSurname]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();setError("");try{await onLogin(surname,password)}catch{setError("Неверная фамилия или пароль")}} return <main className="grid min-h-screen place-items-center bg-cloud p-5"><form onSubmit={submit} className="w-full max-w-md rounded-[2rem] border border-line bg-white p-8 shadow-card"><Building2 className="mb-5 text-brand" size={36}/><h1 className="text-3xl font-semibold">Гостиницы</h1><p className="mt-2 text-muted">Вход для сотрудников компании</p><label className="mt-6 block text-sm font-semibold">Фамилия<input required pattern="[А-Яа-яЁё -]+" value={surname} onChange={e=>setSurname(e.target.value)} className="mt-2 w-full rounded-xl border border-line p-3"/></label><label className="mt-4 block text-sm font-semibold">Пароль<input required inputMode="numeric" pattern="\d{4}" maxLength={4} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-line p-3"/></label>{error&&<p className="mt-4 text-rose-700">{error}</p>}<button className="mt-6 w-full rounded-xl bg-brand p-3 font-semibold text-white">Войти</button></form></main> }

function Editor({hotel,onClose,onSave}:{hotel:Hotel|null,onClose:()=>void,onSave:(v:HotelInput)=>Promise<void>}) { const [v,setV]=useState<HotelInput>(hotel?{name:hotel.name,locality:hotel.locality,address:hotel.address,photo_url:hotel.photo_url,report_amount:hotel.report_amount,actual_price:hotel.actual_price,notes:hotel.notes}:empty); const field=(key:keyof HotelInput,label:string,type="text")=><label className="block text-sm font-semibold">{label}<input type={type} required={key==="name"||key==="report_amount"} min={type==="number"?0:undefined} value={v[key]??""} onChange={e=>setV({...v,[key]:type==="number"?(e.target.value===""?null:Number(e.target.value)):e.target.value})} className="mt-1 w-full rounded-xl border border-line p-3"/></label>; return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-ink/40 p-4"><form onSubmit={e=>{e.preventDefault();onSave(v)}} className="my-6 grid w-full max-w-2xl gap-4 rounded-[2rem] bg-white p-7 shadow-card"><h2 className="text-2xl font-semibold">{hotel?"Изменить гостиницу":"Добавить гостиницу"}</h2>{field("name","Название")}{field("locality","Населённый пункт")}{field("address","Адрес")}{field("report_amount","Сумма по отчёту","number")}{field("actual_price","Фактическая стоимость","number")}{field("photo_url","URL фотографии")}<label className="text-sm font-semibold">Примечание<textarea value={v.notes} maxLength={3000} onChange={e=>setV({...v,notes:e.target.value})} className="mt-1 h-24 w-full rounded-xl border border-line p-3"/></label><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-line px-5 py-3">Отмена</button><button className="rounded-xl bg-brand px-5 py-3 font-semibold text-white">Сохранить</button></div></form></div> }
